---
ios_interfaces:
  GigabitEthernet1/0/1:
    description:         unconfigured
    enabled:             true
    l2:
      access_vlan:       1
      mode:              access
      state:             unconfigured
    l3:
      ipv4:              []
      state:             absent
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/4:
    description:         unconfigured
    enabled:             true
    l2:
      access_vlan:       1
      mode:              access
      state:             unconfigured
    l3:
      ipv4:              []
      state:             absent
    lines:
      - no spanning-tree portfast
    speed:               auto
    state:               present
  GigabitEthernet1/0/5:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/6:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/7:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/10:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/11:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/13:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/15:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/16:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/23:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  # GigabitEthernet1/0/24:
  #   description:       unconfigured
  #   enabled:           true
  #   l2:
  #     access_vlan:     1
  #     mode:            access
  #     state:           unconfigured
  #   speed:             auto
  #   state:             present
  GigabitEthernet1/0/25:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/26:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/27:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/28:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/35:
    description:         Master_Bedroom_ASUS_ASUS5G
    enabled:             true
    lines:               []
    l2:
      access_vlan:       24
      mode:              access
      state:             present
    speed:               auto
    state:               present
  GigabitEthernet1/0/36:
    description:         D-Link_Switch_Uplink
    enabled:             true
    lines:               []
    l2:
      access_vlan:       24
      mode:              access
      state:             present
    speed:               auto
    state:               present
  GigabitEthernet1/0/37:
    description:         Playroom_ASUS_ASUS5G
    enabled:             true
    lines:               []
    l2:
      access_vlan:       24
      mode:              access
      state:             present
    speed:               auto
    state:               present
  GigabitEthernet1/0/38:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/39:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/40:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/41:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/42:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/43:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/44:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/45:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/46:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/47:
    description:         Linksys_Wireless
    enabled:             true
    lines:               []
    l2:
      access_vlan:       24
      mode:              access
      state:             present
    speed:               auto
    state:               present
  GigabitEthernet1/0/48:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/49:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/50:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/51:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  GigabitEthernet1/0/52:
    description:         unconfigured
    enabled:             true
    lines:               []
    speed:               auto
    state:               present
  Vlan10:
    description:         OSPF_Uplink_To_Router
    enabled:             true
    l3:
      ipv4:              10.10.10.3/24
      state:             present
    lines:
      - ip ospf cost 10
    speed:               auto
    state:               present
  Vlan101:
    description:         LAB-101
    enabled:             true
    l3:
      ipv4:              10.0.101.1/24
      state:             present
    lines:
      - ip helper-address 10.10.10.1
    speed:               auto
    state:               present
  Vlan102:
    description:         LAB-102
    enabled:             true
    l3:
      ipv4:              10.0.102.1/24
      state:             present
    lines:               []
    speed:               auto
    state:               present
  Vlan127:
    description:         vMotion
    enabled:             true
    l3:
      ipv4:              []
      state:             absent
    lines:               []
    speed:               auto
    state:               present
  Vlan201:
    description:         DMZ
    enabled:             true
    l3:
      ipv4:              []
      state:             absent
    lines:               []
    speed:               auto
    state:               present
  Vlan24:
    description:         LAN
    enabled:             true
    l3:
      ipv4:              []
      state:             absent
    lines:               []
    speed:               auto
    state:               present
